name: Nightly Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup MSBuild
      uses: warrenbuckley/Setup-MSBuild@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: Restore NuGet Packages (build)
      run: dotnet restore FoxTunes.sln

    - name: Restore NuGet Packages (solution)
      run: nuget restore FoxTunes.sln

    - name: Build x86
      run: msbuild FoxTunes.sln /p:Configuration=Release /property:Platform=x86

    - name: Build x64
      run: msbuild FoxTunes.sln /p:Configuration=Release /property:Platform=x64

    - name: Package
      run: |
        ./release.sh
      shell: bash

    - uses: actions/upload-artifact@v2
      with:
        name: packages
        path: ./release/*.zip
